# -*- coding: utf-8 -*-
"""Testador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGnKI8O609ajSOcEIqFufv2D7Wf7N9kt

# **Teste para maiores de 18!**
"""

def validar_idade(idade):
    """
    Valida se a idade é maior ou igual a 18 anos

    Args:
        idade (int): Idade a ser validada

    Returns:
        bool: True se idade >= 18, False caso contrário

    Raises:
        ValueError: Se a idade não for um número inteiro
    """
    if not isinstance(idade, int):
        raise ValueError("A idade deve ser um número inteiro")

    return idade >= 18

import unittest

class TestValidadorIdade(unittest.TestCase):

    def test_idade_maior_18(self):
        """Testa idades maiores ou iguais a 18 anos"""
        self.assertTrue(validar_idade(18))    # Limite inferior
        self.assertTrue(validar_idade(25))    # Maior que 18
        self.assertTrue(validar_idade(100))   # Idade avançada
        self.assertTrue(validar_idade(30))    # Adulto
        self.assertTrue(validar_idade(21))    # Maioridade em alguns países

    def test_tipo_invalido(self):
        """Testa se levanta exceção para tipos inválidos"""
        with self.assertRaises(ValueError):
            validar_idade("18")      # String
        with self.assertRaises(ValueError):
            validar_idade(18.5)      # Float
        with self.assertRaises(ValueError):
            validar_idade([18])      # Lista
        with self.assertRaises(ValueError):
            validar_idade(None)      # None

    def test_casos_limite_positivos(self):
        """Testa casos limite positivos"""
        self.assertTrue(validar_idade(18))
        self.assertTrue(validar_idade(20))
        self.assertTrue(validar_idade(22))

# Função para verificação interativa
def verificar_idade_interativo():
    """Função para digitar e verificar a idade"""
    print("\n" + "="*50)
    print("VERIFICAÇÃO INTERATIVA DE IDADE")
    print("="*50)

    while True:
        try:
            # Digitar a idade
            entrada = input("\nDigite sua idade (ou 'sair' para terminar): ")

            if entrada.lower() == 'sair':
                print("Encerrando verificação...")
                break

            # Converter para inteiro e validar
            idade = int(entrada)
            resultado = validar_idade(idade)

            # Mostrar resultado
            if resultado:
                print(f"✓ Com {idade} anos: MAIOR DE IDADE")
            else:
                print(f"✗ Com {idade} anos: MENOR DE IDADE")

        except ValueError:
            print("❌ Erro: Digite apenas números inteiros!")
        except Exception as e:
            print(f"❌ Erro inesperado: {e}")

# Executar os testes
if __name__ == '__main__':
    # Primeiro executamos os testes unitários
    print("EXECUTANDO TESTES UNITÁRIOS...")
    print("="*50)

    loader = unittest.TestLoader()
    suite = loader.loadTestsFromTestCase(TestValidadorIdade)
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)

    # Mostrar resultado dos testes
    print(f"\n{'='*50}")
    print(f"Resultado dos testes: {'SUCESSO' if result.wasSuccessful() else 'FALHA'}")
    print(f"Testes executados: {result.testsRun}")
    print(f"Falhas: {len(result.failures)}")
    print(f"Erros: {len(result.errors)}")
    print(f"{'='*50}")

    # Depois executamos a verificação interativa
    verificar_idade_interativo()

"""# **Teste de Impar e Par**"""

def verificar_par_impar(numero):
    """
    Verifica se um número é par ou ímpar

    Args:
        numero (int): Número a ser verificado

    Returns:
        str: 'par' se o número for par, 'ímpar' caso contrário

    Raises:
        ValueError: Se o número não for um inteiro
    """
    if not isinstance(numero, int):
        raise ValueError("O número deve ser um inteiro")

    return 'par' if numero % 2 == 0 else 'ímpar'

import unittest

class TestVerificarParImpar(unittest.TestCase):

    def test_numeros_pares(self):
        """Testa números pares positivos"""
        self.assertEqual(verificar_par_impar(0), 'par')     # Zero é par
        self.assertEqual(verificar_par_impar(2), 'par')     # Par pequeno
        self.assertEqual(verificar_par_impar(10), 'par')    # Par médio
        self.assertEqual(verificar_par_impar(100), 'par')   # Par grande
        self.assertEqual(verificar_par_impar(-4), 'par')    # Par negativo

    def test_numeros_impares(self):
        """Testa números ímpares"""
        self.assertEqual(verificar_par_impar(1), 'ímpar')     # Ímpar pequeno
        self.assertEqual(verificar_par_impar(7), 'ímpar')     # Ímpar médio
        self.assertEqual(verificar_par_impar(99), 'ímpar')    # Ímpar grande
        self.assertEqual(verificar_par_impar(-3), 'ímpar')    # Ímpar negativo

    def test_tipos_invalidos(self):
        """Testa se levanta exceção para tipos inválidos"""
        with self.assertRaises(ValueError):
            verificar_par_impar("5")        # String
        with self.assertRaises(ValueError):
            verificar_par_impar(3.14)       # Float
        with self.assertRaises(ValueError):
            verificar_par_impar([2])        # Lista
        with self.assertRaises(ValueError):
            verificar_par_impar(None)       # None

    def test_casos_limite(self):
        """Testa casos limite interessantes"""
        self.assertEqual(verificar_par_impar(0), 'par')      # Zero
        self.assertEqual(verificar_par_impar(1), 'ímpar')    # Primeiro positivo
        self.assertEqual(verificar_par_impar(-1), 'ímpar')   # Primeiro negativo
        self.assertEqual(verificar_par_impar(2), 'par')      # Primeiro par positivo

# Função para verificação interativa
def verificar_numero_interativo():
    """Função para digitar e verificar se o número é par ou ímpar"""
    print("\n" + "="*60)
    print("🔍 VERIFICADOR DE NÚMERO PAR OU ÍMPAR")
    print("="*60)

    while True:
        try:
            # Digitar o número
            entrada = input("\nDigite um número inteiro (ou 'sair' para terminar): ")

            if entrada.lower() == 'sair':
                print("Encerrando verificação...")
                break

            # Converter para inteiro e verificar
            numero = int(entrada)
            resultado = verificar_par_impar(numero)

            # Mostrar resultado com emojis
            if resultado == 'par':
                print(f"✅ O número {numero} é PAR!")
            else:
                print(f"🔶 O número {numero} é ÍMPAR!")

        except ValueError as e:
            if "invalid literal" in str(e):
                print("❌ Erro: Digite apenas números inteiros!")
            else:
                print(f"❌ Erro: {e}")
        except Exception as e:
            print(f"💥 Erro inesperado: {e}")

# Executar os testes e verificação interativa
if __name__ == '__main__':
    # Primeiro executamos os testes unitários
    print("EXECUTANDO TESTES UNITÁRIOS...")
    print("="*50)

    loader = unittest.TestLoader()
    suite = loader.loadTestsFromTestCase(TestVerificarParImpar)
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)

    # Mostrar resultado dos testes
    print(f"\n{'='*50}")
    print(f"Resultado dos testes: {'✅ SUCESSO' if result.wasSuccessful() else '❌ FALHA'}")
    print(f"Testes executados: {result.testsRun}")
    print(f"Falhas: {len(result.failures)}")
    print(f"Erros: {len(result.errors)}")
    print(f"{'='*50}")

    # Depois executamos a verificação interativa
    verificar_numero_interativo()